CC = gcc
CFLAGS = -Werror -Wextra -Wall
SRCS =
OBJS =

all:

install:

uninstall:

test:

gcov_report:

dvi:

dist:

clean:

style_test:
	clang-format --style=Google -n *.c *.h

google_style:
	clang-format --style=Google -i *.c *.h
